version: 2

sources:
  - name: jaffle_shop
    database: raw
    freshness: # default freshness 1
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: "order_date::timestamp"

    tables:
      - name: orders

      - name: customers # this will use the freshness defined above
        freshness: null

  - name: stripe
    database: raw

    tables:
      - name: payment
        freshness: null # do not check freshness for this table